# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8caaf435fe64ab018910c233c90b7d8b1f1d919ae430715c4f3e1709329bb4005b39a02e27b22796172e744134779f18735f8cc31e59c05fa8989012a831df

test:
  secret_key_base: a61d0cff49f97a28350acdcdf47a1b1ce5a268bd5f50f4c1c1c9efd03020b35a435ba3ca24dfeb3707535d3a22d7b7afcde4e8e9825a4bd915b6c988ef2247ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
